/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'
import { Route as SupplierAnalyticsRouteImport } from './routes/supplier/analytics'
import { Route as SupplierDashboardRouteImport } from './routes/supplier/dashboard'
import { Route as SupplierEnquiriesRouteImport } from './routes/supplier/enquiries'
import { Route as SupplierOnboardingRouteImport } from './routes/supplier/onboarding'
import { Route as SupplierProfileRouteImport } from './routes/supplier/profile'
import { Route as SupplierReviewsRouteImport } from './routes/supplier/reviews'
import { Route as SupplierSettingsRouteImport } from './routes/supplier/settings'
import { Route as SupplierSignupRouteImport } from './routes/supplier/signup'
import { Route as SupplierSubscriptionRouteImport } from './routes/supplier/subscription'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as SuppliersSlugRouteImport } from './routes/suppliers/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/admin/suppliers',
  path: '/admin/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierAnalyticsRoute = SupplierAnalyticsRouteImport.update({
  id: '/supplier/analytics',
  path: '/supplier/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDashboardRoute = SupplierDashboardRouteImport.update({
  id: '/supplier/dashboard',
  path: '/supplier/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierEnquiriesRoute = SupplierEnquiriesRouteImport.update({
  id: '/supplier/enquiries',
  path: '/supplier/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierOnboardingRoute = SupplierOnboardingRouteImport.update({
  id: '/supplier/onboarding',
  path: '/supplier/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProfileRoute = SupplierProfileRouteImport.update({
  id: '/supplier/profile',
  path: '/supplier/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierReviewsRoute = SupplierReviewsRouteImport.update({
  id: '/supplier/reviews',
  path: '/supplier/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSettingsRoute = SupplierSettingsRouteImport.update({
  id: '/supplier/settings',
  path: '/supplier/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSignupRoute = SupplierSignupRouteImport.update({
  id: '/supplier/signup',
  path: '/supplier/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSubscriptionRoute = SupplierSubscriptionRouteImport.update({
  id: '/supplier/subscription',
  path: '/supplier/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSlugRoute = SuppliersSlugRouteImport.update({
  id: '/suppliers/$slug',
  path: '/suppliers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/supplier/analytics': typeof SupplierAnalyticsRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/supplier/enquiries': typeof SupplierEnquiriesRoute
  '/supplier/onboarding': typeof SupplierOnboardingRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/reviews': typeof SupplierReviewsRoute
  '/supplier/settings': typeof SupplierSettingsRoute
  '/supplier/signup': typeof SupplierSignupRoute
  '/supplier/subscription': typeof SupplierSubscriptionRoute
  '/suppliers/$slug': typeof SuppliersSlugRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/supplier/analytics': typeof SupplierAnalyticsRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/supplier/enquiries': typeof SupplierEnquiriesRoute
  '/supplier/onboarding': typeof SupplierOnboardingRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/reviews': typeof SupplierReviewsRoute
  '/supplier/settings': typeof SupplierSettingsRoute
  '/supplier/signup': typeof SupplierSignupRoute
  '/supplier/subscription': typeof SupplierSubscriptionRoute
  '/suppliers/$slug': typeof SuppliersSlugRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/supplier/analytics': typeof SupplierAnalyticsRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/supplier/enquiries': typeof SupplierEnquiriesRoute
  '/supplier/onboarding': typeof SupplierOnboardingRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/reviews': typeof SupplierReviewsRoute
  '/supplier/settings': typeof SupplierSettingsRoute
  '/supplier/signup': typeof SupplierSignupRoute
  '/supplier/subscription': typeof SupplierSubscriptionRoute
  '/suppliers/$slug': typeof SuppliersSlugRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/suppliers'
    | '/admin/verification'
    | '/supplier/analytics'
    | '/supplier/dashboard'
    | '/supplier/enquiries'
    | '/supplier/onboarding'
    | '/supplier/profile'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/signup'
    | '/supplier/subscription'
    | '/suppliers/$slug'
    | '/suppliers/'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/suppliers'
    | '/admin/verification'
    | '/supplier/analytics'
    | '/supplier/dashboard'
    | '/supplier/enquiries'
    | '/supplier/onboarding'
    | '/supplier/profile'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/signup'
    | '/supplier/subscription'
    | '/suppliers/$slug'
    | '/suppliers'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/suppliers'
    | '/admin/verification'
    | '/supplier/analytics'
    | '/supplier/dashboard'
    | '/supplier/enquiries'
    | '/supplier/onboarding'
    | '/supplier/profile'
    | '/supplier/reviews'
    | '/supplier/settings'
    | '/supplier/signup'
    | '/supplier/subscription'
    | '/suppliers/$slug'
    | '/suppliers/'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  SupplierAnalyticsRoute: typeof SupplierAnalyticsRoute
  SupplierDashboardRoute: typeof SupplierDashboardRoute
  SupplierEnquiriesRoute: typeof SupplierEnquiriesRoute
  SupplierOnboardingRoute: typeof SupplierOnboardingRoute
  SupplierProfileRoute: typeof SupplierProfileRoute
  SupplierReviewsRoute: typeof SupplierReviewsRoute
  SupplierSettingsRoute: typeof SupplierSettingsRoute
  SupplierSignupRoute: typeof SupplierSignupRoute
  SupplierSubscriptionRoute: typeof SupplierSubscriptionRoute
  SuppliersSlugRoute: typeof SuppliersSlugRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/analytics': {
      id: '/supplier/analytics'
      path: '/supplier/analytics'
      fullPath: '/supplier/analytics'
      preLoaderRoute: typeof SupplierAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/dashboard': {
      id: '/supplier/dashboard'
      path: '/supplier/dashboard'
      fullPath: '/supplier/dashboard'
      preLoaderRoute: typeof SupplierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/enquiries': {
      id: '/supplier/enquiries'
      path: '/supplier/enquiries'
      fullPath: '/supplier/enquiries'
      preLoaderRoute: typeof SupplierEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/onboarding': {
      id: '/supplier/onboarding'
      path: '/supplier/onboarding'
      fullPath: '/supplier/onboarding'
      preLoaderRoute: typeof SupplierOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/profile': {
      id: '/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof SupplierProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/reviews': {
      id: '/supplier/reviews'
      path: '/supplier/reviews'
      fullPath: '/supplier/reviews'
      preLoaderRoute: typeof SupplierReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/settings': {
      id: '/supplier/settings'
      path: '/supplier/settings'
      fullPath: '/supplier/settings'
      preLoaderRoute: typeof SupplierSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/signup': {
      id: '/supplier/signup'
      path: '/supplier/signup'
      fullPath: '/supplier/signup'
      preLoaderRoute: typeof SupplierSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/subscription': {
      id: '/supplier/subscription'
      path: '/supplier/subscription'
      fullPath: '/supplier/subscription'
      preLoaderRoute: typeof SupplierSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$slug': {
      id: '/suppliers/$slug'
      path: '/suppliers/$slug'
      fullPath: '/suppliers/$slug'
      preLoaderRoute: typeof SuppliersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  SupplierAnalyticsRoute: SupplierAnalyticsRoute,
  SupplierDashboardRoute: SupplierDashboardRoute,
  SupplierEnquiriesRoute: SupplierEnquiriesRoute,
  SupplierOnboardingRoute: SupplierOnboardingRoute,
  SupplierProfileRoute: SupplierProfileRoute,
  SupplierReviewsRoute: SupplierReviewsRoute,
  SupplierSettingsRoute: SupplierSettingsRoute,
  SupplierSignupRoute: SupplierSignupRoute,
  SupplierSubscriptionRoute: SupplierSubscriptionRoute,
  SuppliersSlugRoute: SuppliersSlugRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
