/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierOnboardingRouteImport } from './routes/supplier/onboarding'
import { Route as SupplierSignupRouteImport } from './routes/supplier/signup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierOnboardingRoute = SupplierOnboardingRouteImport.update({
  id: '/supplier/onboarding',
  path: '/supplier/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSignupRoute = SupplierSignupRouteImport.update({
  id: '/supplier/signup',
  path: '/supplier/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supplier/onboarding': typeof SupplierOnboardingRoute
  '/supplier/signup': typeof SupplierSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/supplier/onboarding': typeof SupplierOnboardingRoute
  '/supplier/signup': typeof SupplierSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/supplier/onboarding': typeof SupplierOnboardingRoute
  '/supplier/signup': typeof SupplierSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/supplier/onboarding' | '/supplier/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/supplier/onboarding' | '/supplier/signup'
  id: '__root__' | '/' | '/supplier/onboarding' | '/supplier/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupplierOnboardingRoute: typeof SupplierOnboardingRoute
  SupplierSignupRoute: typeof SupplierSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/onboarding': {
      id: '/supplier/onboarding'
      path: '/supplier/onboarding'
      fullPath: '/supplier/onboarding'
      preLoaderRoute: typeof SupplierOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/signup': {
      id: '/supplier/signup'
      path: '/supplier/signup'
      fullPath: '/supplier/signup'
      preLoaderRoute: typeof SupplierSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupplierOnboardingRoute: SupplierOnboardingRoute,
  SupplierSignupRoute: SupplierSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
